name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-manager:
    uses: ./.github/workflows/build-manager.yml
    secrets: inherit

  release:
    needs:
      - build-manager
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7

      - name: Rename ksud
        run: |
          mkdir -p ksud
          for dir in ./ksud-*; do
              if [ -d "$dir" ]; then
                 echo "----- Rename $dir -----"
                 ksud_platform_name=$(basename "$dir")
                 find "$dir" -type f -name "ksud" -path "*/release/*" | while read -r ksud_file; do
                   if [ -f "$ksud_file" ]; then
                     mv "$ksud_file" "ksud/$ksud_platform_name"
                   fi
                 done
              fi
          done

      - name: Zip AnyKernel3
        run: |
          for dir in AnyKernel3-*; do
            if [ -d "$dir" ]; then
              echo "----- Zip $dir -----"
              (cd $dir && zip -r9 "$dir".zip ./* -x .git .gitignore ./*.zip && mv *.zip ..)
            fi
          done

      - name: Zip WSA kernel
        run: |
          for dir in kernel-WSA-*; do
            if [ -d "$dir" ]; then
              echo "------ Zip $dir ----------"
              (cd $dir && zip -r9 "$dir".zip ./* -x .git .gitignore ./*.zip && mv *.zip ..)
            fi
          done

      - name: Zip ChromeOS ARCVM kernel
        run: |
          for dir in kernel-ARCVM-*; do
            if [ -d "$dir" ]; then
              echo "------ Zip $dir ----------"
              (cd $dir && zip -r9 "$dir".zip ./* -x .git .gitignore ./*.zip && mv *.zip ..)
            fi
          done

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          # PERBAIKAN 1: Ganti 'tag' menjadi 'tag_name'
          tag_name: ${{ github.event_name == 'workflow_dispatch' && format('ci-build-{0}', github.run_number) || github.ref_name }}
          files: |
            # PERBAIKAN 2: Gunakan wildcard **/*.apk agar pasti ketemu
            **/*.apk
            android*-lkm/*_kernelsu.ko
            AnyKernel3-*.zip
            boot-images-*/Image-*/*.img.gz
            kernel-WSA*.zip
            kernel-ARCVM*.zip
            ksud/ksud-*
